services:
  mysql-5.7.41:
    container_name: mysql-5.7.41
    image: mysql:5.7.41
    network_mode: host
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - /opt/ci-tls-mysql:/tls
      - /var/run/mysqld:/var/run/mysqld
    command: >
      /bin/bash -c 'chown -R mysql:mysql /var/run/mysqld && \
        /usr/local/bin/docker-entrypoint.sh mysqld \
          --ssl-ca=/tls/ca-cert.pem \
          --ssl-cert=/tls/server-cert.pem \
          --ssl-key=/tls/server-key.pem
        '

  mysql-8.4.1:
    container_name: mysql-8.4.1
    image: mysql:8.4.1
    network_mode: host
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - /opt/ci-tls-mysql:/tls
      - /var/run/mysqld:/var/run/mysqld
    command: >
      /bin/bash -c 'chown -R mysql:mysql /var/run/mysqld && \
        /usr/local/bin/docker-entrypoint.sh mysqld \
          --mysql-native-password=ON \
          --ssl-ca=/tls/ca-cert.pem \
          --ssl-cert=/tls/server-cert.pem \
          --ssl-key=/tls/server-key.pem
        '
  mysql-9.4.0:
    container_name: mysql-9.4.0
    image: mysql:9.4.0
    network_mode: host
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - /opt/ci-tls-mysql:/tls
      - /var/run/mysqld:/var/run/mysqld
    command: >
      /bin/bash -c 'chown -R mysql:mysql /var/run/mysqld && \
        /usr/local/bin/docker-entrypoint.sh mysqld \
          --ssl-ca=/tls/ca-cert.pem \
          --ssl-cert=/tls/server-cert.pem \
          --ssl-key=/tls/server-key.pem
        '
