#
# Copyright (c) 2019-2024 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

name: Build Linux Docker images

on:
  workflow_dispatch:
  push:
    paths:
      - tools/docker/**


jobs:
  docker-linux:
    strategy:
      matrix:
        include:
          - { image: build-clang3_6,     dockerfile: build-clang3_6,     platforms: "linux/amd64",                }
          - { image: build-clang7,       dockerfile: build-clang7,       platforms: "linux/amd64",                }
          - { image: build-clang11,      dockerfile: build-clang11,      platforms: "linux/amd64",                }
          - { image: build-clang14,      dockerfile: build-clang14,      platforms: "linux/amd64, linux/arm64/v8" }
          - { image: build-clang16,      dockerfile: build-clang16,      platforms: "linux/amd64"                 }
          - { image: build-clang17,      dockerfile: build-clang17,      platforms: "linux/amd64"                 }
          - { image: build-clang18,      dockerfile: build-clang18,      platforms: "linux/amd64"                 }
          - { image: build-clang16-i386, dockerfile: build-clang16-i386, platforms: "linux/amd64"                 }
          - { image: build-gcc5,         dockerfile: build-gcc5,         platforms: "linux/amd64",                }
          - { image: build-gcc6,         dockerfile: build-gcc6,         platforms: "linux/amd64",                }
          - { image: build-gcc10,        dockerfile: build-gcc10,        platforms: "linux/amd64",                }
          - { image: build-gcc11,        dockerfile: build-gcc11,        platforms: "linux/amd64, linux/arm64/v8" }
          - { image: build-gcc13,        dockerfile: build-gcc13,        platforms: "linux/amd64"                 }
          - { image: build-gcc14,        dockerfile: build-gcc14,        platforms: "linux/amd64"                 }
          - { image: build-cmake3_8,     dockerfile: build-cmake3_8,     platforms: "linux/amd64",                }
          - { image: build-noopenssl,    dockerfile: build-noopenssl,    platforms: "linux/amd64",                }
          - { image: build-docs,         dockerfile: build-docs,         platforms: "linux/amd64",                }
          - { image: mysql5,             dockerfile: mysql5,             platforms: "linux/amd64",                }
          - { image: mysql8,             dockerfile: mysql8,             platforms: "linux/amd64, linux/arm64/v8" }
          - { image: mysql9,             dockerfile: mysql9,             platforms: "linux/amd64, linux/arm64/v8" }
          - { image: mariadb,            dockerfile: mariadb,            platforms: "linux/amd64, linux/arm64/v8" }

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: anarthal-containers
          password: ${{ secrets.ANARTHAL_CONTAINERS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: tools/docker/${{ matrix.dockerfile }}.dockerfile
          build-args: ${{ matrix.build-args }}
          platforms: ${{ matrix.platforms }}
          tags: ghcr.io/anarthal-containers/${{ matrix.image }}:${{ github.sha }}, ghcr.io/anarthal-containers/${{ matrix.image }}:latest
